# I prefer to have all routes in one place, so I will not use annotation

#controllers:
#    resource: ../../src/Controller/
#    type: annotation
#
#kernel:
#    resource: ../../src/Kernel.php
#    type: annotation
